{% set name = "pyppmd" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cc04af92f1d26831ec96963439dfb27c96467b5452b94436a6af696649a121fd

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - setuptools >=59
    - setuptools-scm >=6.4.2
  run:
    - python
    - importlib_metadata  # [py<38]
  run_constrained:
    - mypy >=1.10.0

test:
  imports:
    - pyppmd
  commands:
    - pip check
  requires:
    - pip

about:
  description: |
    Classes and functions for compressing and decompressing text data, using
    PPM(Prediction by partial matching) compression algorithm which has several
    variations of implementations.
  home: https://codeberg.org/miurahr/pyppmd
  dev_url: https://codeberg.org/miurahr/pyppmd
  doc_url: https://codeberg.org/miurahr/pyppmd/src/branch/main/README.rst
  summary: PPMd compression/decompression library
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
    - katietz
