{% set name = "pyppmd" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 075c9bd297e3b0a87dd7aeabca7fee668218acbe69ecc1c6511064558de8840f

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - setuptools
    - setuptools-scm
    - wheel
  run:
    - python
    - importlib_metadata  # [py<38]

test:
  imports:
    - pyppmd
  commands:
    - pip check
  requires:
    - pip

about:
  description: |
    Classes and functions for compressing and decompressing text data, using
    PPM(Prediction by partial matching) compression algorithm which has several
    variations of implementations.
  home: https://codeberg.org/miurahr/pyppmd
  dev_url: https://codeberg.org/miurahr/pyppmd
  doc_url: https://codeberg.org/miurahr/pyppmd/src/branch/main/README.rst
  summary: PPMd compression/decompression library
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
    - katietz
